/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'twer' at '8/14/15 9:12 AM' with Gradle 2.2.1
 *
 * @author twer, @date 8/14/15 9:12 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
