/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'twer' at '8/14/15 9:12 AM' with Gradle 2.2.1
 *
 * @author twer, @date 8/14/15 9:12 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
